/**
 * ABI for the BhuSetu LandRegistry smart contract.
 * Auto-extracted from compiled Hardhat artifact — do not edit by hand.
 */
export const LAND_REGISTRY_ABI = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "string", name: "bhuSetuId", type: "string" },
      { indexed: false, internalType: "string", name: "registrationId", type: "string" },
      { indexed: false, internalType: "string", name: "ownerName", type: "string" },
      { indexed: false, internalType: "uint256", name: "landAreaSqFt", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    name: "LandRecorded",
    type: "event",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "exists",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "_bhuSetuId", type: "string" }],
    name: "getRecord",
    outputs: [
      {
        components: [
          { internalType: "string", name: "bhuSetuId", type: "string" },
          { internalType: "string", name: "registrationId", type: "string" },
          { internalType: "uint16", name: "regYear", type: "uint16" },
          { internalType: "uint32", name: "regNumber", type: "uint32" },
          { internalType: "string", name: "ownerName", type: "string" },
          { internalType: "string", name: "ownerEmail", type: "string" },
          { internalType: "string", name: "category", type: "string" },
          { internalType: "uint256", name: "landAreaSqFt", type: "uint256" },
          { internalType: "bool", name: "taxPaid", type: "bool" },
          {
            components: [
              { internalType: "string", name: "north", type: "string" },
              { internalType: "string", name: "south", type: "string" },
              { internalType: "string", name: "east", type: "string" },
              { internalType: "string", name: "west", type: "string" },
            ],
            internalType: "struct LandRegistry.Boundaries",
            name: "boundaries",
            type: "tuple",
          },
          {
            components: [
              { internalType: "string", name: "state", type: "string" },
              { internalType: "string", name: "district", type: "string" },
              { internalType: "string", name: "tehsil", type: "string" },
              { internalType: "string", name: "postOffice", type: "string" },
              { internalType: "string", name: "pincode", type: "string" },
              { internalType: "string", name: "plotNumber", type: "string" },
            ],
            internalType: "struct LandRegistry.Location",
            name: "location",
            type: "tuple",
          },
          {
            components: [
              { internalType: "uint256", name: "processingFee", type: "uint256" },
              { internalType: "uint256", name: "stampDuty", type: "uint256" },
              { internalType: "uint256", name: "totalAmount", type: "uint256" },
            ],
            internalType: "struct LandRegistry.FeeSnapshot",
            name: "fees",
            type: "tuple",
          },
          { internalType: "string[]", name: "documentCids", type: "string[]" },
          { internalType: "address", name: "verifiedBy", type: "address" },
          { internalType: "uint256", name: "verifiedAt", type: "uint256" },
        ],
        internalType: "struct LandRegistry.LandRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_index", type: "uint256" }],
    name: "getRecordByIndex",
    outputs: [
      {
        components: [
          { internalType: "string", name: "bhuSetuId", type: "string" },
          { internalType: "string", name: "registrationId", type: "string" },
          { internalType: "uint16", name: "regYear", type: "uint16" },
          { internalType: "uint32", name: "regNumber", type: "uint32" },
          { internalType: "string", name: "ownerName", type: "string" },
          { internalType: "string", name: "ownerEmail", type: "string" },
          { internalType: "string", name: "category", type: "string" },
          { internalType: "uint256", name: "landAreaSqFt", type: "uint256" },
          { internalType: "bool", name: "taxPaid", type: "bool" },
          {
            components: [
              { internalType: "string", name: "north", type: "string" },
              { internalType: "string", name: "south", type: "string" },
              { internalType: "string", name: "east", type: "string" },
              { internalType: "string", name: "west", type: "string" },
            ],
            internalType: "struct LandRegistry.Boundaries",
            name: "boundaries",
            type: "tuple",
          },
          {
            components: [
              { internalType: "string", name: "state", type: "string" },
              { internalType: "string", name: "district", type: "string" },
              { internalType: "string", name: "tehsil", type: "string" },
              { internalType: "string", name: "postOffice", type: "string" },
              { internalType: "string", name: "pincode", type: "string" },
              { internalType: "string", name: "plotNumber", type: "string" },
            ],
            internalType: "struct LandRegistry.Location",
            name: "location",
            type: "tuple",
          },
          {
            components: [
              { internalType: "uint256", name: "processingFee", type: "uint256" },
              { internalType: "uint256", name: "stampDuty", type: "uint256" },
              { internalType: "uint256", name: "totalAmount", type: "uint256" },
            ],
            internalType: "struct LandRegistry.FeeSnapshot",
            name: "fees",
            type: "tuple",
          },
          { internalType: "string[]", name: "documentCids", type: "string[]" },
          { internalType: "address", name: "verifiedBy", type: "address" },
          { internalType: "uint256", name: "verifiedAt", type: "uint256" },
        ],
        internalType: "struct LandRegistry.LandRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "recordCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "recordIndex",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "bhuSetuId", type: "string" },
          { internalType: "string", name: "registrationId", type: "string" },
          { internalType: "uint16", name: "regYear", type: "uint16" },
          { internalType: "uint32", name: "regNumber", type: "uint32" },
          { internalType: "string", name: "ownerName", type: "string" },
          { internalType: "string", name: "ownerEmail", type: "string" },
          { internalType: "string", name: "category", type: "string" },
          { internalType: "uint256", name: "landAreaSqFt", type: "uint256" },
          { internalType: "bool", name: "taxPaid", type: "bool" },
          {
            components: [
              { internalType: "string", name: "north", type: "string" },
              { internalType: "string", name: "south", type: "string" },
              { internalType: "string", name: "east", type: "string" },
              { internalType: "string", name: "west", type: "string" },
            ],
            internalType: "struct LandRegistry.Boundaries",
            name: "boundaries",
            type: "tuple",
          },
          {
            components: [
              { internalType: "string", name: "state", type: "string" },
              { internalType: "string", name: "district", type: "string" },
              { internalType: "string", name: "tehsil", type: "string" },
              { internalType: "string", name: "postOffice", type: "string" },
              { internalType: "string", name: "pincode", type: "string" },
              { internalType: "string", name: "plotNumber", type: "string" },
            ],
            internalType: "struct LandRegistry.Location",
            name: "location",
            type: "tuple",
          },
          {
            components: [
              { internalType: "uint256", name: "processingFee", type: "uint256" },
              { internalType: "uint256", name: "stampDuty", type: "uint256" },
              { internalType: "uint256", name: "totalAmount", type: "uint256" },
            ],
            internalType: "struct LandRegistry.FeeSnapshot",
            name: "fees",
            type: "tuple",
          },
          { internalType: "string[]", name: "documentCids", type: "string[]" },
        ],
        internalType: "struct LandRegistry.RecordInput",
        name: "input",
        type: "tuple",
      },
    ],
    name: "recordLand",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "registrar",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
