import { Building2, Home, LandPlot } from "lucide-react";

export const properties = [
  {
    id: "#BHU-9928-X",
    title: "Sector 62, Noida Urban",
    price: "₹1.25 Cr",
    area: "1,250 sq.ft",
    type: "Residential",
    typeIcon: Building2,
    status: "Clean Title",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDASUkjc6R5L3aUNdswemylq3mRjXEU4qyX2OSdjjlB9_wkc9EdLMcMetdGSkDNEfUQqZEZp88HqeZJr_1f2Etgi6zsBbt27rTOTbcmhX0acPeToJDYjttYHPlgrbV7s5e8Ywc7I_WaNiKFK63Ot89Q-kOW3y5re4w1cnqCpVqHTK6Eo244blEjSzt_PPKQvFoEvySBnoZVsQ9ACJ5Jt3KcFKQgE9P75Pkl9L9dhWhwaLUNtsTxkqXrz5reQQIic3XSosb15fOC",
    alt: "Modern high-rise apartment building in Noida Sector 62",
  },
  {
    id: "#BHU-4412-Z",
    title: "Whitefield, Bangalore East",
    price: "₹3.80 Cr",
    area: "2,800 sq.ft",
    type: "Villa",
    typeIcon: Home,
    status: "Clean Title",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDeXWJUrB5iCDTyqACqFZ31PloVdfyLMjjOURZ7HiiH5-V5EPsPjFYi9QCXdjqSK5d42go21oFX4-xo1xDJpxvta3MbjdqK9MjFSHgVkUJiMDFskOxZE67AzTp5UpfNFZ9bgc0wvSQGCg4ZVJ8gpQirFHR5IK7fV0pqjOLQlr_YC-ABS99obec8-nCotl5RKZQf5jkJWUZ-MqsVpWsV2afvctkjE2jKJPyLyELTDwlrIIfJn0BlwImRF37vKot90NeGCfA_ui7N",
    alt: "Luxury villa with pool in Whitefield Bangalore",
  },
  {
    id: "#BHU-1029-A",
    title: "New Town, Kolkata Hub",
    price: "₹92.0 L",
    area: "950 sq.ft",
    type: "Open Plot",
    typeIcon: LandPlot,
    status: "Clean Title",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBSGbPiJLrkaYPj4Iglx59TBiHvcxF-YZX7PpsL5cEIrX9SHmDLK6IQ8hUvX8auXudwDwF5lq8imwdqhIbZxrBgNdEYWj0mrxp_InBCRRMdUQYxelkoDZewybVCUtU7pxGx25zQnWoVJremXISGBwkcqPtEzkCfMIMdS46MISeuTh_IrP1mzosNQ5hFb4GJ3XweXy5uqim4LIsgGL5QV3if6vOtLnwFfp2vxd-X0_e2dLF2feOmqYUHzFBiW8XiZ4lqQXgs2NKI",
    alt: "Satellite map view of a plot in New Town Kolkata",
  },
  {
    id: "#BHU-8872-B",
    title: "HITEC City, Hyderabad",
    price: "₹2.45 Cr",
    area: "1,850 sq.ft",
    type: "Commercial",
    typeIcon: Building2,
    status: "Clean Title",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC7HuiUNU90Fa6XsNbjXNAZRPIBQ3oCmjM8jF6jAZV1QWPK_K7UQ06pafh_kZib6nbCLSpesrwsUu0mlpoCmQAfXyCGq8LN6PxP2xOHB4qHmsLLRl4HzJ0N_a3b9bLjip0-mWV3f4V8dECIT-nMqVrIIBLqntiyy3ixMTyaUuYP4GUxcDGo3KykovW9ak50LE-PYZvo4T-ZUD3SaNqYzSZ3rl2u6fIRdh5ZbmY0CA92gJtY0UI2a615y9AhO3O1Vo4xiNLuwjES",
    alt: "Corporate office space in HITEC City Hyderabad",
  },
  {
    id: "#BHU-3341-M",
    title: "Baner, West Pune",
    price: "₹1.85 Cr",
    area: "1,400 sq.ft",
    type: "Apartment",
    typeIcon: Building2,
    status: "Clean Title",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDIr2dbhGCCPzbF1oO6jsNjXYb-BtxLRmlw6I_p_6zb7Ld_xkcQQ1sdpOaxi4BbDAiwLKMBY1c8G8YuiBC491ER3cRRGNMhbSxtBUUxYcrpbH6acHkz3qh82swv-aylcAAfdMgt-yx6UoyYlbi8Ztaqt-V0tcp4YbWfASIajxoxoQk1wnBJJ5937C_vvDwp5xUy0hE4OXcXcdcqmq2n3IHpiYclDMDNQnz8Ny7Yg4GlJCvVKuFGARJbTAqIfw3EzpdsalaNUxy_",
    alt: "Residential apartment interior in Pune",
  },
  {
    id: "#BHU-5521-K",
    title: "Gomti Nagar, Lucknow",
    price: "₹98.5 L",
    area: "1,100 sq.ft",
    type: "Row House",
    typeIcon: Home,
    status: "Clean Title",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCIZIWdkc3NwCorpMOzyyKYG9tN2-N6TZsoGbPvi8AGskxjbLomQffBif8VmtuTOHDeOiE9SiDKvyXiskZMQrQCdkWIWTSggvG0HgSgJc8Gat8upolj0hhEwY40BuPzmJTtSARnuS6lfmUJFE3mBs6kHtF3us4qgtnSyUj3hLoa3CXSA0IAqgUyfo6iiCC7pFghZrgjEUGi6CeldNJGfcjMnWFTwZ8n8HZLZQiCrIykUsk7AbAXQOI_O0nVFAlYpS3iUqDS_KgQ",
    alt: "Residential row house in Lucknow Gomti Nagar",
  },
];
